### PR TITLE
Update anib.py

### PR DESCRIPTION
**Pull request by ytanizaw**
"idx = 0" is needed below line 89?

### CODE REVIEW

**Comment by widdowquinn** [comment]
It may be that both `idx` and `count` need to be moved inside the loop. Can you describe what the problem is with them being outside the loop, and how it is fixed by this change?

I think I know why you want to do this, but if you have noticed a specific problem then it would be great to see a short description.

**Comment by widdowquinn** [comment]
Nope - scratch that, I think you're right - `count` doesn't need to be moved inside the loop.

**Comment by widdowquinn** [comment]
OK - here's what I think the bug does.

If the input sequence is a multi-FASTA sequence, then during the fragmentation step in BLAST database preparation, the sequences are not fragmented correctly. Specifically, the 'cursor' in the sequence is not reset to zero for each sequence in the input file. I have created a new test file to verify/recreate this bug.

I will merge the change, tidy up the duplicate `idx` declaration, and add the test file.

**Comment by widdowquinn** [comment]
Thank you `ytanizaw` - your fix is applied, and I've bumped the version/release to reflect that the change fixes quite a nasty bug.

**Comment by ytanizaw** [comment]
Dear widdowquinn,
That is what I wanted to tell you. Sorry to have confused you with my insufficient description.
Anyway, your scripts are very useful for me.

**Comment by widdowquinn** [comment]
Excellent, I'm very happy to hear that! 

If you spot any more problems, please do submit another issue or PR, as appropriate.

**Pull request merged**
