### PR TITLE
let delta_filter_wrapper.py can run

### PR DESCRIPTION
**Pull request by alienzj**

### CODE REVIEW

**Comment by widdowquinn** [comment]
Hi @alienzj  - what issue does this fix? I believe the script is executable when it is installed.

**Comment by widdowquinn** [comment]
Also, you may like to look at how this will be handled in the next release: https://github.com/widdowquinn/pyani/blob/development/setup.py#L96

**Comment by alienzj** [comment]
I have met some problems when using **pyani** of the master branch ( I have forked it and set PYTHONPATH environment variables to use it)
It can't generate .filter file when using **delta_filter_wrapper.py** to parse .delta file in the pyani workflow.
So let **delta_filter_wrapper.py** to be executed can fix the problem.

**Comment by widdowquinn** [comment]
I see. That's not the recommended or supported route for installation (see https://pyani.readthedocs.io/en/latest/installation.html#pyani-installation). Have you tried using either of the following from the command-line instead?

- `python setup.py install`
- `pip install -e .`

Both of these approaches are standard, and will place executables/helper scripts in the correct places so that `pyani` will work. They are the recommended and supported approaches, and will still work in the next release.

The next release moves from having standalone scripts under `./bin` that get placed as executables, to using entry points within the `pyani` codebase directly, so this modification would have a very short lifespan.

As this fix will be superseded in the next release, and relates only to the undocumented and unsupported way you have used `pyani`, I'm not inclined to merge this PR.

**Comment by alienzj** [comment]
I totally agree with you.

**Comment by widdowquinn** [comment]
Thanks for being so understanding, and also taking the time to put a PR in. Please do keep suggesting improvements - it's very much appreciated!

L.

**Pull request closed without merging**
