### PR TITLE
Add -s flag for species subfolder creation

### PR DESCRIPTION
**Pull request by froggleston**
Add functionality ('-s' flag) to put downloaded files into named species subfolders instead of all in one parent folder. Just an example bit of code, not rigorously tested and could handle subspecies folders better, but it works.

### CODE REVIEW

**Comment by widdowquinn** [comment]
Thanks Rob,

I'll take a proper look at this shortly (just back from a work trip), but from a quick once-over I don't expect any issues. I'm thinking that an alternative string to `--subfolders`, so it notes explicitly that we'd organise by species would be good - any suggestions? 

I'll port it over to the `development` branch for the legacy compatibility script, and the `pyani download` subcommand too, after merging.

Cheers,

L.

**Comment by froggleston** [comment]
Also added some options for a dry run (will go through the motions but not download files), and also for storing the summary files on disk as JSON. You can use both options together if you just want to download the summary files and not the data.

**Comment by froggleston** [comment]
> Thanks Rob,
> 
> That's a good suggestion - much appreciated!
> 
> I'll take a proper look at this shortly (just back from a work trip), but from a quick once-over I don't expect any issues. I'm thinking that an alternative string to `--subfolders`, so it notes explicitly that we'd organise by species, would be good - any suggestions?
> 
> I'll port it over to the `development` branch for the legacy compatibility script, and the `pyani download` subcommand too, after merging.
> 
> Cheers,
> 
> L.

Hmm, outdir_per_species? No idea! :)

**Comment by widdowquinn** [comment]
Thanks Rob! Sorry for the delay.!

I like all the ideas - especially the dry-run and writing summary. I've adopted them, but with some changes and fixes for downstream effects.

- `--subfolders` is now `--subdir_species` (in case we want to do `--subdir_genus` or something, later)
- the summary file extension is now `.json`
- the species directory names are now escaped so that there are no downstream issues with ANI/TETRA
- the `average_nucleotide_identity.py` script is modified to recurse into subdirectories, so it can still be run on the species-split output
- made the logging more verbose

The changes are merged into a049b6 as a new release candidate. Please could you give that commit a look and make sure I've not broken your use cases (too badly).

**Pull request merged**
