### PR TITLE
Sort genomes (for stable anim recovery mode)

### LINKED ISSUE #353: anim nested tree recovery mode follow up
In testing #351 in order to re-run an analysis from last year (August 2020) with the existing ``nucmer_output/`` folder, and different subsets, a small test case finished fairly quickly. A large subset of about 454 entries (out of the original approx 500) has not. Running ``top`` shows it is calling ``nucmer`` and examination of the ``nucmer_output/`` folder shows new/modified files.

Excerpt from the 17 genome example, note 17*16/2 = 136:

```
...
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Generating ANIm command-lines
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling genomes for comparison
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling pairwise comparisons (this can take time for large datasets)...
100%|██████████| 17/17 [00:00<00:00, 387517.22it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...total parwise comparisons to be performed: 136
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Checking database for existing comparison data...
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...after check, still need to run 136 comparisons
[WARNING] [pyani.scripts.subcommands.subcmd_anim]: Entering recovery mode
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Recover mode identified 210692 existing output files for reuse: <snip>.filter (etc)
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Creating NUCmer jobs for ANIm
100%|██████████| 136/136 [00:00<00:00, 526.72it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Running jobs with multiprocessing
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Multiprocessing run completed without error
[INFO] [pyani.scripts.subcommands.subcmd_anim]: ...jobs complete
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Adding comparison results to database...
100%|██████████| 136/136 [00:05<00:00, 25.95it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: ...database updated.
[INFO] [pyani.scripts.pyani_script]: Completed. Time taken: 22.073
...
```

This does not say how many of cached files are of interest (most are from other genomes not needed here), and how many times ``nucmer`` will be called.

A more elaborate test may be needed to verify no ``nucmer`` calls are made when the cached output should already be complete.

I suspect a glitch in path comparison (e.g. relative vs absolute paths), and the current tests passed doing unnecessary re-computation.

Update: typo

### PR DESCRIPTION
**Pull request by peterjc**
This explicitly sorts the FASTA file lists to ensure the genome list is sorted prior to building an all-vs-all matrix. This is important for symmetric methods like anim so that we consistently run ``A_vs_B`` rather than ``B_vs_A`` and thus recovery mode will work stably regardless of the genome order on disk (e.g. cached files have been moved/copied).

Resolves #353 (where examples of both ``A_vs_B`` and ``B_vs_A`` were found on disk).

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [X] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [X] Fork the `pyani` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [X] Set up an appropriate development environment (please see `CONTRIBUTING.md`)
- [X] Create a new branch with a short, descriptive name
- [X] Work on this branch
  - [X] style guidelines have been followed
  - [X] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [ ] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest -v` **non-passing code will not be merged**
- [X] Rebase against `origin/master`
- [X] Check changes with `flake8` and `black` before submission
- [X] Commit branch
- [X] Submit pull request, describing the content and intent of the pull request
- [ ] Request a code review
- [ ] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani/pulls) in the `pyani` repository

### CODE REVIEW

**Comment by peterjc** [comment]
Again a time out on Python 3.6 doing ``tests/test_legacy_scripts.py::test_legacy_anim_mpl``

Tests passed locally on macOS with Python 3.7.12

**Comment by baileythegreen** [comment]
> Does that work? It looks like it changes the object type...

No... you're right. But, also, apparently `Genome` objects aren't sortable.

> How about just swapping to:

```python
if subject.path < query.path:
    query, subject = subject, query  # sort them
```

I was wanting to avoid swapping variable names, but the only concise way of doing that I can see (that works) is slower than the comparison:

```python
query, subject = sorted((A, B), key=lambda _: _.path)
```

and is probably less clear for users. I've removed the sort around the genomes that doesn't work, and added the comparison. Tests pass locally, so I think they will here, too.

**Comment by peterjc** [comment]
I suspected the Genome objects might not be sortable, but didn't check.

I agree sorting with a lambda key function is not as clear - the variable swap seems neatest to me.

**Comment by widdowquinn** [comment]
My 2p.

If this problem is framable as: "We need a stable naming output file scheme that returns the same sets of `A_vs_B.out` filenames, regardless of the order in which genomes are 'seen', on the assumption that A vs B and B vs A give the same output - i.e. the order of query and subject does not matter for the purpose of the analysis" then the simplest option would appear to be to sort genome IDs when composing the output file stem.

With this we could provide:

genome0001 vs genome0002

or 

genome0002 vs genome0001

and _either_ comparison would be written to

`genome0001_vs_genome0002.out` (or similar)

[However, for those pairwise comparisons where direction is important, we have different code that actively reflects the order of query and subject.]

This avoids the need to change any object types, or swap query and subject during the analysis.

**Comment by peterjc** [comment]
Thank you for finishing this and adding tests.

**Pull request merged**
