### PR TITLE
Fixes issue 211: Retain original extensions in `.md5` files

### LINKED ISSUE #211: Preserve extension when naming MD5 hash file?
Quoting the README, you expect files named like this:

```
$ tree C_blochmannia
C_blochmannia
├── GCF_000011745.1_ASM1174v1_genomic.fna
├── GCF_000011745.1_ASM1174v1_genomic.fna.gz
├── GCF_000011745.1_ASM1174v1_genomic.md5
...
```

i.e. When building the expected MD5 hash filename, you drop and replace the extension with ``.md5``.

https://github.com/widdowquinn/pyani/blob/340ed5f4df066e2cbcd5233df8a86d6678f6ff21/pyani/pyani_files.py#L97

However, adding ``.md5`` is a more common convention - recognising for example that ``GCF_000011745.1_ASM1174v1_genomic.fna.md5`` and ``GCF_000011745.1_ASM1174v1_genomic.fna.gz.md5`` would be different. This also allows for other extensions and checksums, like ``GCF_000011745.1_ASM1174v1_genomic.bam.md5``

Usecase: I'm trying to run pyani on a folder of locally assembled FASTA files (not using pyani to download reference assemblies from NCBI), and having discovered the MD5 files were essential ran: ``for f in *.fasta; do md5sum $f > $f.md5; done`` - workaround ``$ for f in *.fasta; do md5sum $f > ${f%.*}.md5; done``

Suggestion One: Replace ``stem.md5`` with ``stem.ext.md5`` as hashfile for FASTA file ``stem.ext``

Suggestion Two: Allow ``stem.ext.md5`` as well as ``stem.md5`` given FASTA file ``stem.ext``

### PR DESCRIPTION
**Pull request by baileythegreen**
Please include a summary of the change and which issue is fixed. Please also include the motivation and context, and note the tests that apply to these changes.

Fixes #211. This PR changes the naming of hash files generated by `$ pyani index` so that the original file extension is preserved, following discussion in #211.

The relevant test target files (`tests/test_targets/submd_index/*.md5`) have been renamed to reflect the altered behaviour, as has `pyani_files.py`.

This last file has been modified such that it first looks for a hash file where the extension has been retained. If one is not found, it then looks for one where the original extension has been replaced with `.md5`. This was done to provide backwards compatibility.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] This change requires a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md`)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed
  - [x] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [x] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest -v` **non-passing code will not be merged**
- [x] Rebase against `origin/master`
- [x] Check changes with `flake8` and `black` before submission
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [x] Request a code review
- [ ] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani/pulls) in the `pyani` repository

### CODE REVIEW

**Review by widdowquinn — COMMENTED** [review]
This bit looks good

**Review by widdowquinn — CHANGES_REQUESTED** [review]
Please could we have the first failure (ll. 100-101) raise an error with `logger.warning()` rather than writing to `sys.stderr`.

In general, messages to the user should go through the logger.

**Review by widdowquinn — COMMENTED** [review]
Looks good

**Review by widdowquinn — COMMENTED** [review]
Looks good

**Review by widdowquinn — CHANGES_REQUESTED** [review]
Would it please be possible to add a test to catch line 107? A call to `get_fasta_and_hash_paths()` where the hash is genuinely missing should do it.

**Comment by baileythegreen** [comment]
I've made the changes with the logger, and added a test for a case where no hash file with either accepted name is found.

If this was not what you wanted the new test to check, let me know.

**Review by widdowquinn — COMMENTED** [review]
In terms of "atomic commits", each commit should ideally leave the code in a functional state, so I would have combined this change (adding the `logger.warning()` call) with the previous one (removing the `sys.stderr.write()` calls).

Where a message is split over two lines indicating one action taken as the consequence of another, I try to indicate this with ellipses, e.g.

```text
Hashfile A.fas.md5 does not exist...
...trying A.md5
```

**Review by widdowquinn — COMMENTED** [review]
Typo (not that it really matters…): should be `nonexistent_hash.fna`

**Review by widdowquinn — CHANGES_REQUESTED** [review]
I think this should raise the `PyaniFilesException` instead of `IOError`, e.g l.142

```python
raise PyaniFilesException(f"Could not load hash file {filename}.")
```

The idea behind this is that using the custom `Exception`s identifies things that are considered errors by `pyani` and/or noticed by `pyani`, rather than those which occur for other reasons. This helps triage problems - a built-in error is something going wrong that we might need to attend to to fix a bug; custom exceptions indicate we've seen the problem and made a decision on how to handle it.

**Comment by baileythegreen** [comment]
I think all of the requested changes have been made.

**Review by widdowquinn — APPROVED** [review]
All looks good - thank you!

**Pull request merged**
