### PR TITLE
Fix genome labels in matrix output

### LINKED ISSUE #357: Default labels in matrix output, 1:1 2:2 3:3 etc
#### Summary:

Matrix output is not applying labels, e.g. example with 17 genomes:

```
$ head -n 1 matrix_identity_1.tab 
1:1	2:2	3:3	4:4	5:5	6:6	7:7	8:8	9:9	10:10	11:11	12:12	13:13	14:14	15:15	16:16	17:17
```

#### Description:

The problem is a string vs integer mapping, cross reference b54106f36428f017a2589b05de33c0a6d3ed9ea4 (15 Oct 2019) addressing a similar issue with Seaborn plotting.

#### Reproducible Steps:

I have added debug logging:

```
$ git diff
diff --git a/pyani/scripts/subcommands/subcmd_report.py b/pyani/scripts/subcommands/subcmd_report.py
index 3b1d1bb..6d79009 100644
--- a/pyani/scripts/subcommands/subcmd_report.py
+++ b/pyani/scripts/subcommands/subcmd_report.py
@@ -263,6 +263,8 @@ def subcmd_report(args: Namespace) -> int:
             logger.debug("Extracting matrices for run %s", run_id)
             run = session.query(Run).filter(Run.run_id == run_id).first()
             matlabel_dict = get_matrix_labels_for_run(session, run_id)
+            logger.debug("Have %i matrix labels for run", len(matlabel_dict))
+            logger.debug("Matrix labels %s", matlabel_dict)
             for matdata in [
                 MatrixData(*_)
                 for _ in [
@@ -277,7 +279,9 @@ def subcmd_report(args: Namespace) -> int:
                 matrix = pd.read_json(matdata.data)
                 # Matrix rows and columns are labelled if there's a label dictionary,
                 # and take the dataframe index otherwise
+                logger.debug("Matrix columns before labels %s...", repr(matrix.columns)[:150])
                 matrix = label_results_matrix(matrix, matlabel_dict)
+                logger.debug("Matrix columns after labels %s...", repr(matrix.columns)[:150])
                 pyani_report.write_dbtable(
                     matrix,
                     Path(
```

This shows ``matlabel_dict`` is loaded by function ``get_matrix_labels_for_run`` with string keys, ``'1'`` to ``'17'``. See b54106f36428f017a2589b05de33c0a6d3ed9ea4 which added string casting.

However, function ``label_results_matrix`` is still looking up integer row/column indexes, and finding no match and applying the default value giving label strings of ``'1:1'``, ..., ``'17:17'`` instead.

I think we need a string cast in ``label_results_matrix`` prior to dictionary lookup, but fear side effects... this fixes my example, PR to follow.

(Updated - was trying the tests without the development environment active)

### PR DESCRIPTION
**Pull request by peterjc**
Closed #357 - matrix output is not applying labels, e.g. example with 17 genomes:

```
$ head -n 1 matrix_identity_1.tab 
1:1	2:2	3:3	4:4	5:5	6:6	7:7	8:8	9:9	10:10	11:11	12:12	13:13	14:14	15:15	16:16	17:17
```

The problem is a string vs integer mapping, cross reference b54106f36428f017a2589b05de33c0a6d3ed9ea4 (15 Oct 2019) addressing a similar issue with Seaborn plotting.

Where might a test be best added?

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [X] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [X] Fork the `pyani` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [X] Set up an appropriate development environment (please see `CONTRIBUTING.md`)
- [X] Create a new branch with a short, descriptive name
- [X] Work on this branch
  - [X] style guidelines have been followed
  - [X] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [ ] tests for the change have been added that demonstrate the fix or feature works
- [X] Test locally with `pytest -v` **non-passing code will not be merged**
- [X] Rebase against `origin/master`
- [X] Check changes with `flake8` and `black` before submission
- [X] Commit branch
- [X] Submit pull request, describing the content and intent of the pull request
- [ ] Request a code review
- [ ] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani/pulls) in the `pyani` repository

### CODE REVIEW

**Comment by baileythegreen** [comment]
I think, on the subject of testing, this is going to require updating unittest targets to reflect what the output should look like, rather than adding a different test. But first, I need to know what the final output is intended to look like, as mentioned in #357.

**Comment by baileythegreen** [comment]
This PR says I merged it, but I don't remember doing this, and don't know why I would, as the discussion indicates more changes are probably needed. I am also not being given a way to revert the merge, so that's fun. This is not the only weird behaviour I've noticed today, so....

**Comment by peterjc** [comment]
I would have left it as is (merged), but if you fancy looking at the matrix output sooner rather than later fair enough.

**Comment by baileythegreen** [comment]
I have put this on branch `pr_358` (which was my local name for it) and re-submitted it as a new PR: #https://github.com/widdowquinn/pyani/pull/361.

I prefer to do both things at once, so the discussion is less convoluted (though, I realise the GItHub issues I've just had mean that ship has kind of sailed).

@peterjc You can clone that branch to your fork if you want to add anything to it, or decide that Leighton and I can handle it, in which case I will look at it after my viva next week.

**Comment by peterjc** [comment]
I'll leave this with you - good luck with your viva!

**Pull request merged**
