### PR TITLE
Restore nested anim folders to avoid N^2 files per directory

### PR DESCRIPTION
**Pull request by peterjc**
This reverts commit f15cbb06abf14d71ef51d0fa8f1d5e85d27db18b included on PR #276.

That commit undid my deliberate use of nested anim folders in #217 (as discussed on #220, this greatly helped the file system when doing hundreds of comparisons).

Hopefully the automated tests will flush out why this was done... and let me try reusing my 500 genome comparison set with the nested structure.

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [X] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [X] Fork the `pyani` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md`)
- [X] Create a new branch with a short, descriptive name
- [X] Work on this branch
  - [X] style guidelines have been followed
  - [X] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [x] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest -v` **non-passing code will not be merged**
- [X] Rebase against `origin/master`
- [X] Check changes with `flake8` and `black` before submission
- [X] Commit branch
- [X] Submit pull request, describing the content and intent of the pull request
- [x] Request a code review
- [ ] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani/pulls) in the `pyani` repository

### CODE REVIEW

**Comment by widdowquinn** [comment]
Thanks @peterjc - I think this is valuable behaviour, but I reverted it because it breaks a bunch of tests and that was confusing matters while we were working on two other problems: #276 and implementing the SLURM wrapper (the `pr_236` branch, not merged for reasons we've discussed elsewhere). The quickest fix at the time was reverting - I should have raised another issue.

I don't quite understand why PRs from forks don't trigger the CircleCI tests to let us know they break things but, for info, here's what results:

```text
========================================= short test summary info ==========================================
FAILED tests/test_anim.py::test_maxmatch_single - FileNotFoundError: [Errno 2] No such file or directory:...
FAILED tests/test_anim.py::test_mummer_multiple - AssertionError: assert (['nucmer --m...ile4.filter']) =...
FAILED tests/test_anim.py::test_mummer_single - FileNotFoundError: [Errno 2] No such file or directory: '...
FAILED tests/test_concordance.py::test_anim_concordance - FileNotFoundError: [Errno 2] No such file or di...
FAILED tests/test_legacy_scripts.py::test_legacy_anim_sns - pyani.anim.PyaniANImException: /private/var/f...
FAILED tests/test_legacy_scripts.py::test_legacy_anim_mpl - pyani.anim.PyaniANImException: /private/var/f...
================ 6 failed, 92 passed, 1 skipped, 2 xfailed, 2 warnings in 514.39s (0:08:34) ================
```

If you run `pytest -v` locally, hopefully you can confirm the failures and address them for a PR?

Cheers,

L.

**Review by widdowquinn — CHANGES_REQUESTED** [review]
Currently breaks tests - see comment in the discussion thread.

**Comment by widdowquinn** [comment]
I've modified the configuration so we should now run CI on PRs from forks (in a limited way to avoid credential exposure…) so I ought not to be fooled by the green "All checks have passed" mark and merge prematurely, in future.

**Comment by peterjc** [comment]
What I could read of the test failures in your comment suggest minor updates to the tests to reflect the nested paths are needed.

Running locally I get test failures with anim, but it looks like _same_ failures on master. Might be down to the version of mummer? I used conda with a manual hash-bang fix for https://github.com/bioconda/bioconda-recipes/issues/28209

**Comment by peterjc** [comment]
Cross reference #294

**Comment by widdowquinn** [comment]
> Running locally I get test failures with anim, but it looks like _same_ failures on master. 

I don't see any failures on `master`, locally. It also passes the remote tests.

> Might be down to the version of mummer? I used conda with a manual hash-bang fix for [bioconda/bioconda-recipes#28209](https://github.com/bioconda/bioconda-recipes/issues/28209)

That's possible. AFAICT there are a few broken `bioconda` recipes of late (I hit `t-coffee` and `parsnp` issues earlier today on Linux…). If I wanted to manually fix my shebangs I wouldn't bother with `conda`… ;)

What version did you install, finally?

**Comment by peterjc** [comment]
The problematic mummer on macOS self-reports as:

```
$ nucmer --version
nucmer 
NUCmer (NUCleotide MUMmer) version 3.1
```

Based on conda with the hash-bang lines edited manually:

```
$ conda list | grep mummer
mummer                    3.23                h589c0e0_12    bioconda
```

I will try an older package later in the hopes that's what is breaking things.

**Comment by peterjc** [comment]
Updating ``test_anim_concordance`` in ``tests/test_concordance.py`` needs a bit more effort...

Likewise I think I need to get the test suite working locally before understanding where ``tests/test_legacy_scripts.py`` is breaking.

**Comment by baileythegreen** [comment]
@peterjc If you include the output for the failed tests run with `pytest -v` (std. error output, not a log file), I can help identify what is causing the test suite to break, in case you don't want to take the time to decipher it.

**Comment by peterjc** [comment]
Now that CircleCI is running, I can see useful errors, e.g.

```
INFO     pyani.scripts.average_nucleotide_identity:average_nucleotide_identity.py:558 Processing NUCmer .delta files.
INFO     pyani.anim:anim.py:358 /tmp/pytest-of-circleci/pytest-0/test_legacy_anim_sns0/nucmer_output has 0 files to load
ERROR    pyani.anim:anim.py:360 /tmp/pytest-of-circleci/pytest-0/test_legacy_anim_sns0/nucmer_output empty? No filter files found
```

Meanwhile locally I have yet to solve the mummer issue:

```
======================================== short test summary info ========================================
FAILED tests/test_concordance.py::test_anim_concordance - SystemExit: Zero length alignment!
FAILED tests/test_legacy_scripts.py::test_legacy_anim_sns - SystemExit: Zero length alignment!
FAILED tests/test_legacy_scripts.py::test_legacy_anim_mpl - SystemExit: Zero length alignment!
FAILED tests/test_subcmd_04_anim.py::TestANImSubcommand::test_anim - pyani.PyaniException: Multiproces...
FAILED tests/test_subcmd_05_report.py::TestReportSubcommand::test_matrices - ValueError: Invalid file ...
FAILED tests/test_subcmd_06_plot.py::TestPlotSubcommand::test_plot_mpl_jpg - ValueError: Invalid file ...
FAILED tests/test_subcmd_06_plot.py::TestPlotSubcommand::test_plot_mpl_pdf - ValueError: Invalid file ...
FAILED tests/test_subcmd_06_plot.py::TestPlotSubcommand::test_plot_mpl_png - ValueError: Invalid file ...
FAILED tests/test_subcmd_06_plot.py::TestPlotSubcommand::test_plot_mpl_svg - ValueError: Invalid file ...
FAILED tests/test_subcmd_06_plot.py::TestPlotSubcommand::test_plot_seaborn_jpg - ValueError: Invalid f...
FAILED tests/test_subcmd_06_plot.py::TestPlotSubcommand::test_plot_seaborn_pdf - ValueError: Invalid f...
FAILED tests/test_subcmd_06_plot.py::TestPlotSubcommand::test_plot_seaborn_png - ValueError: Invalid f...
FAILED tests/test_subcmd_06_plot.py::TestPlotSubcommand::test_plot_seaborn_svg - ValueError: Invalid f...
FAILED tests/test_subcmd_07_classify.py::TestClassifySubcommand::test_classify_defaults - ValueError: ...
FAILED tests/test_subcmd_07_classify.py::TestClassifySubcommand::test_classify_no_thresh - ValueError:...
============== 15 failed, 84 passed, 1 xfailed, 1 xpassed, 8 warnings in 497.43s (0:08:17) ==============
```

I will try installing an older BioConda package and/or installing from source.

**Comment by peterjc** [comment]
OK, that is working locally for me now,

```
$ pytest -v
...
=================== 99 passed, 1 xfailed, 1 xpassed, 10 warnings in 540.27s (0:09:00) ===================
```

**Comment by widdowquinn** [comment]
One failed run first-time through at CircleCI - rerunning, now.

@baileythegreen - this is a model for what the BLAST/fastANI/other methods should be doing. Would you prefer we merge/close this PR and raise a new issue for those, or handle the changes now and extend the PR to include those methods?

**Comment by peterjc** [comment]
Looks like Python 3.6 on CircleCI timed out during ``tests/test_legacy_scripts.py::test_legacy_anim_mpl``

**Comment by widdowquinn** [comment]
> Looks like Python 3.6 on CircleCI timed out during `tests/test_legacy_scripts.py::test_legacy_anim_mpl`

Twice, now.

**Comment by baileythegreen** [comment]
> this is a model for what the BLAST/fastANI/other methods should be doing

@widdowquinn You mean putting output files in a subdirectory in `outdir`? fastANI does this as of last week. I think I need to make this change in anib/lastall still. I'll do that on the appropriate branch. No real need for y'all to do anything.

**Comment by widdowquinn** [comment]
> > this is a model for what the BLAST/fastANI/other methods should be doing
> 
> @widdowquinn You mean putting output files in a subdirectory in `outdir`? 

Exactly - nesting output. It saves a lot of filesystem bother with large jobs.

> fastANI does this as of last week. I think I need to make this change in anib/lastall still. I'll do that on the appropriate branch. No real need for y'all to do anything.

Excellent! I'm checking python 3.6 tests locally, and when (if…) they pass I'll merge this.

**Comment by widdowquinn** [comment]
Hit the usual `mummer` `bioconda` issue, and a wee bit of trouble with my local `pytest` install, but the 3.6 tests complete locally - merging this.

Thanks for the enhancement and tests, @peterjc!

**Pull request merged**
