### PR TITLE
Fixes issue 262: Streamline behaviour of `--version` and `--citation` flags

### LINKED ISSUE #262: The `--version` flag does not work (as expected)
#### Summary:
The `--version` flag, common to almost every software program, throws an error in the development version fo `pyani`. (I do not know about v2.)

Additionally, I think that one should be able to run `pyani --citation`, with no subcommand, and get the `pyani` citation info back.

#### Current Output:
```
$ pyani --version
usage: pyani.py [-h] {download,index,createdb,anim,anib,aniblastall,report,plot,classify,listdeps} ...
pyani.py: error: unrecognized arguments: --version
```

#### Expected Output:
```
$ pyani --version
pyani 0.3.0-alpha
```
(or whichever version it is)

#### pyani Version:
dev

### PR DESCRIPTION
**Pull request by baileythegreen**
Fixes #262. Implements commonly-expected functionality for the `--version` and `--citation` options at both the `pyani` and subcommand levels. Changes include addition of missing options to `__init__.py` and `common_parser.py`, checks and processing for these two options in `pyani_script.py`, and short-version flags added to some subcommand parsers to prevent errors related to 'missing positional arguments'.

The appropriate behaviour when these options are called along with a subcommand where `--version` or `--citation` information doesn't make sense, perhaps needs to be discussed.

### CODE REVIEW

**Comment by widdowquinn** [comment]
There are four aspects of the behaviour of these options I would like please to have changed. Overall, I would expect the `--version`/`--citation` behaviour to have this behaviour:

- provide information when `pyani` is called without subcommands
- ignored when a subcommand is used
  - (the version/citation info can be obtained using the `-v` verbose option already when using subcommands; there is no functional reason to call `pyani` in isolation without a subcommand except to get help/other static info)
- when both `--version` and `--citation` are requested, provide both version and citation information

## 1. Behaviour when both arguments are specified

The commands `pyani --version` and `pyani --citation` behave reasonably, but I think that a user issuing both options together should expect the longer form output with both version and citation information, e.g.:

### Expected behaviour

```bash
$ pyani --citation
pyani version: 0.3.0-alpha

CITATION INFO:

If you use pyani in your work, please cite the following publication:
	Pritchard, L., Glover, R. H., Humphris, S., Elphinstone, J. G.,
	& Toth, I.K. (2016) 'Genomics and taxonomy in diagnostics for
	food security: soft-rotting enterobacterial plant pathogens.'
	Analytical Methods, 8(1), 12–24. http://doi.org/10.1039/C5AY02550H
$ pyani --version --citation
pyani version: 0.3.0-alpha

CITATION INFO:

If you use pyani in your work, please cite the following publication:
	Pritchard, L., Glover, R. H., Humphris, S., Elphinstone, J. G.,
	& Toth, I.K. (2016) 'Genomics and taxonomy in diagnostics for
	food security: soft-rotting enterobacterial plant pathogens.'
	Analytical Methods, 8(1), 12–24. http://doi.org/10.1039/C5AY02550H
$ pyani --citation --version
pyani version: 0.3.0-alpha

CITATION INFO:

If you use pyani in your work, please cite the following publication:
	Pritchard, L., Glover, R. H., Humphris, S., Elphinstone, J. G.,
	& Toth, I.K. (2016) 'Genomics and taxonomy in diagnostics for
	food security: soft-rotting enterobacterial plant pathogens.'
	Analytical Methods, 8(1), 12–24. http://doi.org/10.1039/C5AY02550H
```

### Current behaviour

```bash
$ pyani --version --citation
pyani.py 0.3.0-alpha
$ pyani --citation --version
pyani.py 0.3.0-alpha
```

## 2. Behaviour when a subcommand is issued

The `--version` and `--citation` arguments block execution of subcommands. For instance:

### Current behaviour

```bash
$ pyani createdb -f
[WARNING] [pyani.scripts.subcommands.subcmd_createdb]: Database .pyani/pyanidb already exists - overwriting
$ pyani createdb -f --version
pyani 0.3.0-alpha
$ pyani createdb -f --citation
pyani 0.3.0-alpha
If you use pyani in your work, please cite the following publication:
	Pritchard, L., Glover, R. H., Humphris, S., Elphinstone, J. G.,
	& Toth, I.K. (2016) 'Genomics and taxonomy in diagnostics for
	food security: soft-rotting enterobacterial plant pathogens.'
	Analytical Methods, 8(1), 12–24. http://doi.org/10.1039/C5AY02550H
```

The `--version` and `--citation` flags should be ignored when a subcommand is provided (the information is already available with the -v option).

### Expected behaviour:

```bash
$ pyani createdb -f
[WARNING] [pyani.scripts.subcommands.subcmd_createdb]: Database .pyani/pyanidb already exists - overwriting
$ pyani createdb -f --version
[WARNING] [pyani.scripts.subcommands.subcmd_createdb]: Database .pyani/pyanidb already exists - overwriting
$ pyani createdb -f --citation
[WARNING] [pyani.scripts.subcommands.subcmd_createdb]: Database .pyani/pyanidb already exists - overwriting
```

## 3. `--citation` output is inconsistent

The `--citation` flag should give the same output whenever it is called. Truncated output is given when passed with a subcommand (see above). This problem will go away when (2) above is implemented, as the `--citation` option will have no effect when issued with subcommands.

## 4. `pyani` called on its own should be equivalent to `pyani -h` rather than `pyani --version` - this gives more information to the user about how to use the package.

**Review by widdowquinn — CHANGES_REQUESTED** [review]
Please see notes on option behaviour in main discussion.

**Comment by baileythegreen** [comment]
Related to point 4, what would you like to do about the citations for the dependencies? Do you always want that to be produced along with `pyani` citation information, or should there be some way to only get one or the other?

**Comment by widdowquinn** [comment]
> Related to point 4, what would you like to do about the citations for the dependencies? Do you always want that to be produced along with `pyani` citation information, or should there be some way to only get one or the other?

My view of the `--citation` option is that it exists to give people a quick way to find out how to cite `pyani`. I don't think we need to include dependencies in that output.

If the `-v`/`--verbose` output is given for any activity, citations to the main analysis-relevant dependencies are given as a way of acknowledging their (unwitting) contribution, which is a different motivation. I don't think we need to provide an additional option for the user to obtain this information.

**Comment by baileythegreen** [comment]
New behaviour of code in this pull request, which I believe meets all of the specifications set out above:

```bash
$ pyani --version
pyani version: 0.3.0-alpha

$ pyani --citation
pyani version: 0.3.0-alpha

If you use pyani in your work, please cite the following publication:
	Pritchard, L., Glover, R. H., Humphris, S., Elphinstone, J. G.,
	& Toth, I.K. (2016) 'Genomics and taxonomy in diagnostics for
	food security: soft-rotting enterobacterial plant pathogens.'
	Analytical Methods, 8(1), 12–24. http://doi.org/10.1039/C5AY02550H

$ pyani --version --citation
pyani version: 0.3.0-alpha

If you use pyani in your work, please cite the following publication:
	Pritchard, L., Glover, R. H., Humphris, S., Elphinstone, J. G.,
	& Toth, I.K. (2016) 'Genomics and taxonomy in diagnostics for
	food security: soft-rotting enterobacterial plant pathogens.'
	Analytical Methods, 8(1), 12–24. http://doi.org/10.1039/C5AY02550H

$ pyani --citation --version
pyani version: 0.3.0-alpha

If you use pyani in your work, please cite the following publication:
	Pritchard, L., Glover, R. H., Humphris, S., Elphinstone, J. G.,
	& Toth, I.K. (2016) 'Genomics and taxonomy in diagnostics for
	food security: soft-rotting enterobacterial plant pathogens.'
	Analytical Methods, 8(1), 12–24. http://doi.org/10.1039/C5AY02550H

$ pyani createdb -f
[WARNING] [pyani.scripts.subcommands.subcmd_createdb]: Database .pyani/pyanidb already exists - overwriting

$ pyani createdb -f --version
[WARNING] [pyani.scripts.subcommands.subcmd_createdb]: Database .pyani/pyanidb already exists - overwriting

$ pyani createdb -f --citation
[WARNING] [pyani.scripts.subcommands.subcmd_createdb]: Database .pyani/pyanidb already exists - overwriting

$ pyani
usage: pyani.py [-h] [--version] [--citation]
                {download,index,createdb,anim,anib,aniblastall,report,plot,classify,listdeps} ...

optional arguments:
  -h, --help            show this help message and exit
  --version
  --citation            Display pyani citation (default: False)

subcommands:
  valid subcommands

  {download,index,createdb,anim,anib,aniblastall,report,plot,classify,listdeps}
                        additional help

$ pyani -h
usage: pyani.py [-h] [--version] [--citation]
                {download,index,createdb,anim,anib,aniblastall,report,plot,classify,listdeps} ...

optional arguments:
  -h, --help            show this help message and exit
  --version
  --citation            Display pyani citation (default: False)

subcommands:
  valid subcommands

  {download,index,createdb,anim,anib,aniblastall,report,plot,classify,listdeps}
                        additional help
```

**Comment by baileythegreen** [comment]
Anything else to be done here? Do we want tests for this?

**Comment by widdowquinn** [comment]
I was waiting for the tests to finish and got distracted.

I'm equivocal about tests for this - they'd be good to have for completeness, but as this isn't output-critical code I'm happy for that to be low priority.

**Review by widdowquinn — APPROVED** [review]

**Pull request merged**
