### PR TITLE
Issue 48: Describe `pyani plot` graphical output.

### LINKED ISSUE #48: Description of Heatmap Outputs
#### Summary:
I'm familiar with ANI (and there is a very good description of it in the README), so the *_percentage_identity, *_alignment_length, and *_alignment_coverage make sense to me.

I'm not so sure about the *_hadamard or *_similarity_errors graphs.  Is there a good resource to find out more as to how to interpret these?  Or the algorithms used to generate them?

#### Operating System: Fedora 23

### LINKED ISSUE #303: ANIm ouput files need some explanation
I am using pyani and it is great, easy to use with nice figures. Yet, I need more information regarding some of the output data that I get with ANIm and I can´t find it anywhere else. Please help!

I am running pyani for a large multispecies dataset and my goal is to get ANIm estimations of all pairwise genome comparisons so I can estimate average intraspecific and interspecific ANIm.

I need help interpreting these output files:
ANIm_alignment_coverage
ANIm_alignment_lengths
ANIm_hadamard
ANIm_similarity_errors

And I am not sure if I can trust results for which I got ANIm=0.84 but
alignment coverage = 0.10, 
alignment  length = 1/10 of intraspecific alignment length
Hadamard=0.09 while intraspecific is 0.98
Similarity error file does vary according to intra/interspecific comparisons.

Thanks
Patricia

#### pyani Version:
pyani 0.2.11

#### installed dependencies
installed with conda

### PR DESCRIPTION
**Pull request by baileythegreen**
Adds descriptions of `pyani plot` graphical output (based on responses to Issues #48 and #303, as well as how things are calculated in the code).

Not ready to be merged, but ready for discussion of what else should be included / if anything needs to be removed.

Fixes #48.
Fixes #303.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [x] This is a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md`)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed
  - [ ] new code is commented, especially in hard-to-understand areas
  - [x] corresponding changes to documentation have been made
  - [ ] tests for the change have been added that demonstrate the fix or feature works
- [ ] Test locally with `pytest -v` **non-passing code will not be merged**
- [ ] Rebase against `origin/master`
- [ ] Check changes with `flake8` and `black` before submission
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [ ] Request a code review
- [ ] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani/pulls) in the `pyani` repository

### CODE REVIEW

**Review by widdowquinn — COMMENTED** [review]
I think that "interpreting output" belongs under "Basic Use" in the ToC, rather than at the same level as "installation" and requirements" - please can we link it from `basic_use.rst` instead?

`ANIb`/`ANIblastall`/TETRA methods will be available in v0.3, so I don't think we should note a restriction there. (ll.51-55)

I'll not merge this until you've decided whether TETRA is symmetrical or not and changed the text. (l.55)

We should avoid double newlines (I think they're formatted the same, regardless…) (l.61)

Is the description on l.65 correct? It sounds like alignment length uses the length of the reference genome, as phrased.

The alignment length/similarity errors should be described for ANIb/ANIblastall methods (they don't crop up for TETRA).

l.75 is missing an "as" or "because", I think.

**Comment by baileythegreen** [comment]
I took l.65 from the docstring in `anim.parse_delta()`, l.270. That says 'reference_length', but I don't know if that means it's right.

**Comment by widdowquinn** [comment]
> I took l.65 from the docstring in `anim.parse_delta()`, l.270. That says 'reference_length', but I don't know if that means it's right.

Yes, that's not entirely clear is it? Especially out of the immediate context.

`reference_length` there means: "the number of bases from the reference sequence in the alignment."

I think this needs clarification in the documentation certainly, but maybe also a note in the comment at that point in the code might be useful.

**Comment by baileythegreen** [comment]
I've made those changes.

Are there any situations where coverage should be symmetrical, actually? Unless I've misunderstood them (and notes in the docstrings are wrong, in some cases) none of these methods are. In which case the explanation I lifted from one of your issue comments about how coverage 'can be' asymmetrical might need to be changed.

**Comment by widdowquinn** [comment]
> Are there any situations where coverage should be symmetrical, actually?

Two come to mind:

- Any situation where the alignment is symmetrical, and the participating genomes have the same lengths.
- Any situation where the alignment is not symmetrical, but the participating genomes happen to compensate by being different lengths.

It would be trivial to generate a completely symmetrical coverage output by renaming a single input file multiple times, and pretending they were different genomes.

> Unless I've misunderstood them (and notes in the docstrings are wrong, in some cases) none of these methods are. 

ANIb/ANIblastall are not symmetrical.

TETRA is described here: https://doi.org/10.1111/j.1462-2920.2004.00624.x - having reminded myself with a quick skim, I think the pairwise score is calculated by:

1. determining the frequency Z-score for each possible 4-mer in the sequence of each genome (i.e. the normalised deviation from "expected frequency")
2. calculating a Pearson correlation coefficient between the two Z-score vectors

which sounds symmetrical to me. What are your thoughts?

> In which case the explanation I lifted from one of your issue comments about how coverage 'can be' asymmetrical might need to be changed.

The mathematician in me tries to stop me from claiming that something is always true, if it is not. A common method of (dis)proof is the counterexample. The counterexamples above, contrived or coincidental as they might be, demonstrate that coverage can be symmetrical. If you feel that we need to state a stronger expectation of asymmetry, how about "will usually be asymmetrical"?

**Comment by widdowquinn** [comment]
I think there's opportunity for an IJSEM paper discussing how algorithm choice affects measurement, along the lines of https://doi.org/10.1099/ijsem.0.004124

**Comment by baileythegreen** [comment]
I think that brief description of TETRA sounds symmetrical, however, you previously indicated that 

> alignment length/similarity errors...don't crop up for TETRA

from this, I extrapolated that coverage also didn't apply. It isn't calculated in `tetra.py` as far as I can see (and is certainly not named as such), and all of the calculations of coverage depend upon an alignment length.

Did I misunderstand something, or infer too much?

***

> If you feel that we need to state a stronger expectation of asymmetry, how about "will usually be asymmetrical"?

My issue is purely with the combination of 'this can be asymmetrical', as though this is a possible, but low-probability event, followed by 'every method we implement is asymmetrical (almost always)'. "[W]ill usually be symmetrical" resolves this.

**Comment by baileythegreen** [comment]
The description for similarity errors in ANIm should perhaps be modified. Currently, this does not use what NUCmer/MUMmer themselves identify as `similarity errors`, but `non-identities + indels`. The discrepancy could lead to confusion if people try to compare across tools (whether or not such comparisons actually make sense).

**Comment by widdowquinn** [comment]
I've checked the docs here and made modifications where necessary (e.g. alignment length in the BLAST methods does not subtract mismatches; adding summaries of the scatterplot/distribution output).

NOTE: we will need to modify the descriptions of some measures when we correct ANIm calculations according to #340

**Pull request merged**
