### PR TITLE
Fixes issue 232: Pyani throws an error when it fails to find 3rd-party tool versions (but they are installed)

### LINKED ISSUE #232: pyani listdeps broken :: pyani/aniblastall.py :: blastall doe not have --version option
#### Summary:
running `pyany listdeps` from fresh cloned repo (commit 0081885c0c5c81e6885a533279c56749c5c12bd4)
I have the following error

```
Installed third-party tool versions...
	blast+==Linux_2.10.0+
	nucmer==Linux_3.1
Traceback (most recent call last):
  File "/opt/gensoft/exe/pyani/0.3.0a0/bin/pyani", line 8, in <module>
    sys.exit(run_main())
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/scripts/pyani_script.py", line 105, in run_main
    returnval = args.func(args)
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/scripts/subcommands/subcmd_listdeps.py", line 86, in subcmd_listdeps
    for tool, version in get_tool_versions():
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/dependencies.py", line 117, in get_tool_versions
    yield (name, func())
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/aniblastall.py", line 74, in get_version
    version = re.search(  # type: ignore
AttributeError: 'NoneType' object has no attribute 'group'
```

#### pyani Version:
pyani does not provide a way to know his version ;-)
a `--version` flag will be nice.

anyway 
```
average_nucleotide_identity.py --version 
average_nucleotide_identity.py: pyani 0.3.0-alpha
```
code clone from commit 0081885c0c5c81e6885a533279c56749c5c12bd4

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

see above problem ;-)

```
System information
        Platorm==Linux-4.18.0-193.19.1.el8_2.x86_64-x86_64-with-glibc2.2.5
        Python==3.8.1 (default, May 22 2020, 14:09:57)
[GCC 9.2.0]
Installed pyani Python dependendencies...
        Pillow==8.1.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        biopython==1.78 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        matplotlib==3.3.3 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        namedlist==1.8 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        networkx==2.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        numpy==1.19.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        openpyxl==Not Installed (-)
        pandas==1.2.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        scipy==1.6.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        seaborn==0.11.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        sqlalchemy==1.3.22 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        tqdm==4.56.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
Installed pyani development dependendencies...
        bandit==Not Installed (-)
        black==Not Installed (-)
        coverage==Not Installed (-)
        doc8==Not Installed (-)
        flake8==Not Installed (-)
        jinja2==Not Installed (-)
        mypy==Not Installed (-)
        pydocstyle==Not Installed (-)
        pylint==Not Installed (-)
        pytest==Not Installed (-)
        pytest-cov==Not Installed (-)
        sphinx==Not Installed (-)
Installed pyani pip-install dependendencies...
        pre-commit==Not Installed (-)
        pytest-ordering==Not Installed (-)
        sphinx-rtd-theme==Not Installed (-)
Installed third-party tool versions...
        blast+==Linux_2.10.0+
        nucmer==Linux_3.1
Traceback (most recent call last):
  File "/opt/gensoft/exe/pyani/0.3.0a0/bin/pyani", line 8, in <module>
    sys.exit(run_main())
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/scripts/pyani_script.py", line 105, in run_main
    returnval = args.func(args)
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/scripts/subcommands/subcmd_listdeps.py", line 86, in subcmd_listdeps
    for tool, version in get_tool_versions():
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/dependencies.py", line 117, in get_tool_versions
    yield (name, func())
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/aniblastall.py", line 74, in get_version
    version = re.search(  # type: ignore
AttributeError: 'NoneType' object has no attribute 'group'
```

problem is that `blastall` does not provide a --version  option. when called `blastall --version` it display an error message.
tested with legacy blast 2.2.19, 2.2.21, 2.2.25, 2.2.26.

```
tars-submit0:~ > blastall --version 
[blastall] ERROR: Invalid argument: --version
``` 
it should be called with `--help` instead of `--version`

furthermore blastall output in this case is deirected to `stdout` not `stderr`

changing code from 
```
This is concatenated with the OS name.
    """
    cmdline = [blast_exe, "-version"]
    result = subprocess.run(
        cmdline,  # type: ignore
        shell=False,
        stdout=subprocess.PIPE,  # type: ignore
        stderr=subprocess.PIPE,
        check=False,  # blastall doesn't return 0
    )
    version = re.search(  # type: ignore
        r"(?<=blastall\s)[0-9\.]*", str(result.stderr, "utf-8")
    ).group()
```
to 
```
    This is concatenated with the OS name.
    """
    cmdline = [blast_exe, '--help']
    result = subprocess.run(
        cmdline,  # type: ignore
        shell=False,
        stdout=subprocess.PIPE,  # type: ignore
        stderr=subprocess.PIPE,
        check=False,  # blastall doesn't return 0
    )
    
    version = re.search(  # type: ignore
        r"(?<=blastall\s)[0-9\.]*", str(result.stdout, "utf-8")
```

fix the problem see:

```
pyani listdeps 2>&1| tee log
System information
	Platorm==Linux-4.18.0-193.19.1.el8_2.x86_64-x86_64-with-glibc2.2.5
	Python==3.8.1 (default, May 22 2020, 14:09:57) 
[GCC 9.2.0]
Installed pyani Python dependendencies...
	Pillow==8.1.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	biopython==1.78 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	matplotlib==3.3.3 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	namedlist==1.8 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	networkx==2.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	numpy==1.19.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	openpyxl==Not Installed (-)
	pandas==1.2.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	scipy==1.6.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	seaborn==0.11.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	sqlalchemy==1.3.22 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	tqdm==4.56.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
Installed pyani development dependendencies...
	bandit==Not Installed (-)
	black==Not Installed (-)
	codecov==Not Installed (-)
	coverage==Not Installed (-)
	doc8==Not Installed (-)
	flake8==Not Installed (-)
	jinja2==Not Installed (-)
	mypy==Not Installed (-)
	pydocstyle==Not Installed (-)
	pylint==Not Installed (-)
	pytest==Not Installed (-)
	pytest-cov==Not Installed (-)
	sphinx==Not Installed (-)
Installed pyani pip-install dependendencies...
	pre-commit==Not Installed (-)
	pytest-ordering==Not Installed (-)
	sphinx-rtd-theme==Not Installed (-)
Installed third-party tool versions...
	blast+==Linux_2.10.0+
	nucmer==Linux_3.1
	blastall==Linux_2.2.26
[gensoft@345ddfccadad pyani-0.3.0a0]$ 
[gensoft@345ddfccadad pyani-0.3.0a0]$ pyani listdeps 2>&1| tee log
System information
	Platorm==Linux-4.18.0-193.19.1.el8_2.x86_64-x86_64-with-glibc2.2.5
	Python==3.8.1 (default, May 22 2020, 14:09:57) 
[GCC 9.2.0]
Installed pyani Python dependendencies...
	Pillow==8.1.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	biopython==1.78 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	matplotlib==3.3.3 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	namedlist==1.8 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	networkx==2.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	numpy==1.19.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	openpyxl==Not Installed (-)
	pandas==1.2.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	scipy==1.6.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	seaborn==0.11.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	sqlalchemy==1.3.22 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	tqdm==4.56.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
Installed pyani development dependendencies...
	bandit==Not Installed (-)
	black==Not Installed (-)
	codecov==Not Installed (-)
	coverage==Not Installed (-)
	doc8==Not Installed (-)
	flake8==Not Installed (-)
	jinja2==Not Installed (-)
	mypy==Not Installed (-)
	pydocstyle==Not Installed (-)
	pylint==Not Installed (-)
	pytest==Not Installed (-)
	pytest-cov==Not Installed (-)
	sphinx==Not Installed (-)
Installed pyani pip-install dependendencies...
	pre-commit==Not Installed (-)
	pytest-ordering==Not Installed (-)
	sphinx-rtd-theme==Not Installed (-)
Installed third-party tool versions...
	blast+==Linux_2.10.0+
	nucmer==Linux_3.1
	blastall==Linux_2.2.26
```

hope this will help

regards

Eric

### PR DESCRIPTION
**Pull request by baileythegreen**
Please include a summary of the change and which issue is fixed. Please also include the motivation and context, and note the tests that apply to these changes.

Fixes #232. A user reported Pyani failing to find a version for `blastall` when `pyani listdeps` was run, but `blastall` *was* installed.

It appeared to be caused by OS-dependent differences in the output of the command to obtain `blastall`'s version. (User was using Linux.)

Just removing the `"-version"` part of the command line then caused the error on MacOS.

This PR switches the command line used based on OS, and also gently reports failure to obtain a version number for *any* third-party tool.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md`)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed
  - [ ] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [ ] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest -v` **non-passing code will not be merged**
- [x] Rebase against `origin/master`
- [x] Check changes with `flake8` and `black` before submission
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [x] Request a code review
- [x] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani/pulls) in the `pyani` repository

### CODE REVIEW

**Review by widdowquinn — APPROVED** [review]

**Review by widdowquinn — CHANGES_REQUESTED** [review]
I think we should have `get_<PROGRAM>_version()` return the "could not retrieve version" string.

**Comment by baileythegreen** [comment]
Are you going to say the same thing about #218? I get that handling errors at a lower level is potentially desirable, but so is not repeating code if we don't have to (like, if we wanted to handle it differently depending on the tool).

I don't know if there may also be more errors we will want to handle at this particular spot in the code, but if we handle them in `get_<tool>_version()`, whatever error handling we do there will need to be added into new third-party tools, as well.

**Comment by widdowquinn** [comment]
> Are you going to say the same thing about #218?

Yes.

> I don't know if there may also be more errors we will want to handle at this particular spot in the code, but if we handle them in `get_<tool>_version()`, whatever error handling we do there will need to be added into new third-party tools, as well.

More than one approach could make sense here, but here's my reasoning:

- Catch an `AttributeError` in `dependencies.py` assumes that an `AttributeError` is thrown, but this is not defined behaviour - so we'd want to ensure that called methods do throw an `AttributeError`, which is an extra definition of expected behaviour and still requires editing of individual `get_<PROGRAM>_version()` functions.

- With similar effort, we could standardise responses along the lines of:
  - no executable found: raise response 1
  - executable found but version not retrieved: raise response 2 

and then test specifically for those responses. This is potentially clearer and self-documenting.

**Comment by baileythegreen** [comment]
Okay, well, I will still need to catch an error at the lower level. `flake8` doesn't like bare `except:`s, so can I catch the `AttributeError` (and `FileNotFoundError` for 218, there) or do you want me to do that a different way?

**Comment by widdowquinn** [comment]
I've added some cases that catch the various types of error we might encounter. Here I've chosen to test for the specific circumstances of the kind of error we might encounter, to aid with diagnostics. This helps when the same class of error (e.g. `OSError`) might be thrown by more than one kind of event. This code catches:

- no file at path
- file at path, but not executable
- executable doesn't return a version we can use
- returned version

Also, there's a new issue since macOS 11 in that the compiled legacy BLAST executable won't run on Big Sur and later. The added code catches `OSError` and returns a string noting that the executable is there, but we can't run it.

I've also modified the "success" string so it has a similar format to that returned for the libraries. See what you think.

**Comment by baileythegreen** [comment]
Looks good. It definitely goes against the "it's better to ask for forgiveness, than permission", Python philosophy, but it's more informative for the user, so it can't be bad.

I've gone and added the equivalent code to the `fastANI` branch, so that doesn't get overlooked later.

**Comment by widdowquinn** [comment]
The EAFP approach is fine a lot of the time, but sometimes there are side effects, and sometimes it contradicts the "explicit is better than implicit" guideline. Here I think it's better to be explicit ("this is what the problem is") than implicit ("there's an attribute error, and one of the several ways in which this could have failed happened").

It's a judgement call.

**Comment by baileythegreen** [comment]
Experimenting with mocking to test the new `get_version()` checks in `anib.py`. The test is passing, so I guess it works, but I'll see what the coverage looks like.

If everything looks good, I would plan on doing the equivalent things for the other subcommands.

**Comment by baileythegreen** [comment]
`anib.py` coverage now looks good. Will work on the other files.

**Comment by baileythegreen** [comment]
@widdowquinn

Can you share the output (traceback and all) that you get if you try to run `pyani blastall` on your newer version of macOS? I'm trying to write a test for that bit, but so far failing to mock it properly, and think seeing the actual behaviour might help.

Specifically, I'm having trouble getting an OSError to be raised.

**Comment by baileythegreen** [comment]
Nevermind! As often happens, immediately after requesting help/insight/what have you, the solution has become apparent. (Or, rather, the reason the solution wasn't quite working has.)

New commits to follow shortly.

**Comment by baileythegreen** [comment]
I suspect you'll want some of the things in `conftest.py` to be renamed or moved around, but I'll leave them as they are for now.

**Comment by widdowquinn** [comment]
> Can you share the output (traceback and all) that you get if you try to run `pyani blastall` on your newer version of macOS? 

Sadly, no - legacy BLAST is an unmaintained compiled binary and does not run on MacOS 11.

**Comment by widdowquinn** [comment]
Ah, right - I see what you mean. What happens when I try to, e.g. `os.system("blastall")`?

```python
>>> import os
>>> os.system("blastall")
sh: /Users/lpritc/opt/anaconda3/envs/pyani_py38/bin/blastall: Bad CPU type in executable
32256
```

**Comment by baileythegreen** [comment]
Yes, that. I think I was trying to figure out how I would catch it so I could find something that would intentionally throw the same thing. That was proving difficult to do without knowing what the thing I wanted to catch looked like.

**Comment by baileythegreen** [comment]
I'm restoring the branch for this because I had not yet pulled the more recent changes, and I want to study the tests.

**Comment by widdowquinn** [comment]
They should be on `master` after merging… (e.g. https://github.com/widdowquinn/pyani/blob/master/tests/test_aniblastall.py)

**Comment by baileythegreen** [comment]
In writing tests for PR #335, I have begun to question this bit of code:

```python
 nucmer_path = Path(shutil.which(nucmer_exe))  # type:ignore

 if nucmer_path is None:
    return f"{nucmer_exe} is not found in $PATH"
```

I don't think `if nucmer_path is None` is ever going to evaluate to `True`, or even run (because `None` is not what `shutil.which()` returns when it fails to find a file). If I set the `nucmer_exe` value in `pyani_config.py` to an arbitrary value (e.g., `NUCMER_DEFAULT = Path("ehfjmoijh")`), then try to run `pyani listdeps`, what I get is:

```python
Traceback (most recent call last):
  File "/Users/baileythegreen/Software/miniconda3/bin/pyani", line 11, in <module>
    load_entry_point('pyani', 'console_scripts', 'pyani')()
  File "/Users/baileythegreen/Software/pyani/pyani/scripts/pyani_script.py", line 126, in run_main
    returnval = args.func(args)
  File "/Users/baileythegreen/Software/pyani/pyani/scripts/subcommands/subcmd_listdeps.py", line 86, in subcmd_listdeps
    for tool, version in get_tool_versions():
  File "/Users/baileythegreen/Software/pyani/pyani/dependencies.py", line 117, in get_tool_versions
    yield (name, func())
  File "/Users/baileythegreen/Software/pyani/pyani/anim.py", line 113, in get_version
    nucmer_path = Path(shutil.which(nucmer_exe))  # type:ignore
  File "/Users/baileythegreen/Software/miniconda3/lib/python3.8/pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "/Users/baileythegreen/Software/miniconda3/lib/python3.8/pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Users/baileythegreen/Software/miniconda3/lib/python3.8/pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I propose modifying this to the following:

```python
    try:
        nucmer_path = Path(shutil.which(nucmer_exe))  # type:ignore
        # if nucmer_path is None:
    except TypeError:
        return f"{nucmer_exe} is not found in $PATH"
```

which then allows `pyani listdeps` to exit gracefully (and informatively):

```bash
Installed third-party tool versions...
	blast+==Darwin_2.6.0+ (/Users/baileythegreen/Software/miniconda3/bin/blastn)
	nucmer==ehfjmoijh is not found in $PATH
	blastall==Darwin_2.2.26 (/Users/baileythegreen/Software/miniconda3/bin/blastall)
```

I will incorporate these changes into #335, where I am adding other tests for `get_version()`.

**Pull request merged**
