### PR TITLE
Fix anim recovery mode

### PR DESCRIPTION
**Pull request by peterjc**
I found anim was not reusing pre-existing files.

My fix was using Path object directly, not just the filename (which discards the path information). Could alternatively have built or converted the expected list into filenames only?

Also turns the list of Path objects into a set for a slight speed up (addresses a TODO comment), and adds a bit more debugging.

As far as I can see, anib does not support recovery mode (untested)?

### CODE REVIEW

**Comment by widdowquinn** [comment]
I've just hit on a similar problem when moving between systems to try to repeat an analysis. The hard-coded path stored in the `pyani` database is a problem under that circumstance. This may take a wee while to look into and find a common solution.

**Comment by widdowquinn** [comment]
Also, ANIb is not properly implemented in v0.3.x yet - it will support a recovery mode, at some point.

**Comment by peterjc** [comment]
I've not looked at the paths in the DB - my first choice would be store them relative to the DB location if they are within the same parent folder; absolute otherwise.

If it is easier to fix this as part of that work, please close this and go ahead - I can use this PR's branch locally in the meantime.

**Comment by widdowquinn** [comment]
I'm thinking about whether to make the comparison dependent - by default - only on the hash, not the path at all, but provide an option whereby the user can specify that they want to recalculate if either the filenames, or the paths, don't match (i.e. one option for each - mutually exclusive, taking the "most specific" as highest priority).

**Comment by peterjc** [comment]
Sounds interesting medium/long term; my fix is useful right now.

**Comment by peterjc** [comment]
Found a problem, testing a fix. Even with these changes, pre-computed delta files were not being loaded into the DB.

**Comment by widdowquinn** [comment]
I see this is mentioned in #220 as having an issue - are you working on the fix?

**Comment by peterjc** [comment]
Fix from yesterday, plus work for #220 (a separate commit so could be separated).

Worked on the big dataset of ~500 genomes; would like to do more testing on a small set with interruptions etc - but will not be able to until later this week.

**Comment by peterjc** [comment]
Testing on a small test set works nicely, e.g. fresh run, full recover, partial recovery.

**Comment by widdowquinn** [comment]
Do you think you might be able to document your test procedure, or even turn it into a test under `tests`?

**Comment by peterjc** [comment]
You don't have any SGE CI tests do you? Well, it ought to work with multiprocessing just the same...

**Comment by widdowquinn** [comment]
Sadly not - I haven't worked out how to do SGE on CircleCI, yet :(

**Review by widdowquinn — APPROVED** [review]

**Comment by widdowquinn** [comment]
I think we'll need new tests to ensure this works…

**Comment by peterjc** [comment]
Great - this branch was working well on our old institute cluster under SGE, but I've not be able to run it since as we've moved to SLURM.

**Comment by widdowquinn** [comment]
Not 100% sure it's working properly on SLURM, yet - I've hit a couple more issues just now. I'll look into it.

**Comment by peterjc** [comment]
Oh excellent, I'd missed that you'd started working on SLURM support  👍

**Pull request merged**
